### PR TITLE
Add the first version of V17 Flat file for silicon

### PR DESCRIPTION
**Pull request by bsunanda**
This is the flat file for V17 silicon

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by jfernan2** [comment]
+1

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@jfernan2 Could you sign it again?

**Comment by bsunanda** [comment]
@perrotta @qliphy can this be integrated?

**Comment by emanueleusai** [comment]
+1

**Comment by smuzaffar** [comment]
@bsunanda , as this PR just adds a new data file, is there any cms-sw/cmssw PR to test/use it?

**Comment by bsunanda** [comment]
I have tested this with the code HGCalConvert.cpp in Geometry/HGCalCommonData/test and ran using test/slc7_am664_gcc10/HGCalConvert <inpfile> 2 silEE0.txt silHEsil0.txt silHEmix0.txt 0 0

**Comment by smuzaffar** [comment]
@bsunanda , so are you planning to open a cmssw PR ? I am fine with signing this and including it in cmssw but it would be nice to have a test to use it to make sure the contents of new data files are good.

**Comment by bsunanda** [comment]
@smuzaffar Could you please merge this PR at your earliest convenience. We need this file within CMSSW for validation.

**Comment by smuzaffar** [comment]
+externals
only new file, should be safe to include it for next IB

**Comment by smuzaffar** [comment]
@bsunanda , this is merged now and will be available in tonight's 23h00 12.4.X IB

**Pull request merged**
