### PR TITLE
ScintillayorV19X2: Add the next version of the scintillator flat file

### PR DESCRIPTION
**Pull request by bsunanda**
Add the next version of the scintillator flat file. This will be the first description of the V19 geometry of HGCal with low- and high-density tiles.

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@nothingface0, @rvenditti, @syuvivida, @tjavaid Please approve this PR

**Comment by tjavaid** [comment]
@bsunanda , could you please add a bit more to the PR description and explain the content of file ? Are the [changes](https://tinyurl.com/2moy8r99) expected ?

**Comment by bsunanda** [comment]
Added some more explanations
________________________________

**Comment by tjavaid** [comment]
> Are the [changes](https://tinyurl.com/2moy8r99) expected ?

Could you please also respond to this ?

**Comment by bsunanda** [comment]
Yes they are expected. We have not yet finalised the geometry specification. It will be done only when the construction is completed and that will be in 2028-29. So this is our present understanding.
________________________________

**Comment by tjavaid** [comment]
+1

**Comment by smuzaffar** [comment]
@bsunanda , this PR just adds a new data file, is there any cmssw PR to use/test it?

**Comment by bsunanda** [comment]
My answer will be the same as for PR #8
________________________________

**Comment by bsunanda** [comment]
@smuzaffar Please integrate this for 14_1_X

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
