### PR TITLE
ScintillatorV19VX Add the first version of the V19 flat file for scintillators

### PR DESCRIPTION
**Pull request by bsunanda**
Add the first version of the HGCal V19 flat file for scintillators

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@aandvalenzuela, @nothingface0, @tjavaid, @antoniovagnerini, @syuvivida, @rvenditti Could you please approve this PR

**Comment by bsunanda** [comment]
@smuzaffar I request this PR to be merged. This is again the first file to initiate the V19 geometry. Once we complete that version we shall need this file to complete validation

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
