### PR TITLE
WaferCSV Add the geometry file needed for new validation of v16 and v17 geometries

### PR DESCRIPTION
**Pull request by bsunanda**
Add the geometry file needed for the new validation of v16 and v17 geometries. These files are needed to run HGCalCellHitSum (analyzer for muon tomography)

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar, @aandvalenzuela, @emanueleusai, @iarspider, @ahmad3213 Please add these 2 files to cmsdata - needed for validation

**Comment by bsunanda** [comment]
@smuzaffar, @aandvalenzuela, @emanueleusai, @iarspider, @ahmad3213 Could you merge this PR to a new version of cms-data for CMSSW_12_5_X

**Comment by emanueleusai** [comment]
+1

**Comment by bsunanda** [comment]
@smuzaffar Could you merge this PR to master and make a new er version of cms-data?

**Comment by smuzaffar** [comment]
+externals
 new files only
@qliphy  @perrotta feel free to merge it

**Comment by perrotta** [comment]
+1

**Pull request merged**
