### PR TITLE
Scintillator: Add the first version of flat file for scintillator

### PR DESCRIPTION
**Pull request by bsunanda**
This is the flat file for. the scintillator part. To be used for validation of HGCal Geometry

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar Kindly add this file to cms_data

**Comment by bsunanda** [comment]
@smuzaffar, @aandvalenzuela, @emanueleusai, @iarspider, @ahmad3213 Could you merge this PR to a new version of cms-data for CMSSW_12_5_X

**Comment by emanueleusai** [comment]
+1

**Comment by bsunanda** [comment]
@smuzaffar Could you merge this PR to master and make a new er version of cms-data?

**Comment by smuzaffar** [comment]
+externals

contains only new data files
@qliphy @perrotta , @rappoccio feel free to merge it and the cmsdist PR which bot will open.

**Comment by perrotta** [comment]
+1

**Pull request merged**
