### PR TITLE
validation of hgcal geometry

### PR DESCRIPTION
**Pull request by smuzaffar**
- Added hgcal geometry validation data file
- Move existing `.xo` files from https://github.com/cms-sw/cmssw/tree/master/Validation/HGCalValidation/data here

### CODE REVIEW

**Comment by smuzaffar** [comment]
ping

**Comment by smuzaffar** [comment]
DQM L2's ,  @bsunanda requested to add hgcal geometry validation data file. In cmssw/Validation/HGCalValidation/data package there are already couple of `.xo` files which I would also like to move in cms-data , so I also included those file in this PR. Later we will delete the  cmssw/Validation/HGCalValidation/data. 

Do you have any objections ion including this ?

**Comment by apsallid** [comment]
Hi @smuzaffar , 

There is a DQM plot that uses the file, so the path [here](https://github.com/cms-sw/cmssw/blob/master/Validation/HGCalValidation/python/HGCalValidator_cfi.py#L49) should be updated in another pull request.  I can do it, but how do use access these files in cms-data with cms.FileInPath ?

**Comment by apsallid** [comment]
@smuzaffar A ok sorry, I just saw your message, no action is needed! Thanks.

**Comment by smuzaffar** [comment]
@apsallid , yes path for data files (either from cmssw or cms-data) accessed via `FileInPath` remains the same. Once this is merged and included in cmssw then we can safely drop `.xo` files from cmssw.

**Comment by smuzaffar** [comment]
as @bsunanda need to develop on top of this, so I suggest that we merge it and include it in next IB.

**Comment by jfernan2** [comment]
+1
For the records

**Pull request merged**
