### PR TITLE
SiliconV19VX Add the first version of V19 Flat file for silicon

### PR DESCRIPTION
**Pull request by bsunanda**
V19 version of the flat file for the description of silicon modules of HGCal

### CODE REVIEW

**Comment by bsunanda** [comment]
@cmsbuild Please test

**Comment by bsunanda** [comment]
@smuzaffar Could you please merge this file

**Comment by bsunanda** [comment]
@aandvalenzuela, @nothingface0, @tjavaid, @antoniovagnerini, @syuvivida, @rvenditti Could you please approve this PR

**Comment by smuzaffar** [comment]
@bsunanda , this is a new data file, is there any cmssw PR to make use of it? If yes then I would suggest to start the tests from cmssw PR to make sure that data file was properly read/used

**Comment by bsunanda** [comment]
Not yet. It will take a long while to finish V19 of HGCal geometry and the validation of that version will utilize this file. The new file is. the input with which we start and then we make a complete V19 geometry version of HGCal which requires new algorithms and many major changes.
________________________________

**Comment by smuzaffar** [comment]
ok, as #6 and #7 just add new data files so I merging these now for 14.1.X

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@bsunanda , both #6 and #7 are now merged and should be available in today's 11h00 14.1.X IB

**Pull request merged**
